### ISSUE TITLE
Upgrade to Spring Boot 2.1.0

### ISSUE THREAD

**Issue by ghost** [fourscouts/blog#1]
Did You try upgrade project to String Boot 2.1.0? After upgrade I have problem with not existing variable authentication.name in my ThymeLeaf template. Any ideas what is reason of this issue?

**Comment by ghost** [comment]
Of course i talking about "oauth2-discord".

**Comment by rsuurd** [comment]
Hey ol-funky, sorry for the late reply.

To solve your problem, you need to upgrade the thymeleaf extras spring security dependency to use spring security 5 rather than 4:
 `org.thymeleaf.extras:thymeleaf-extras-springsecurity5:3.0.4.RELEASE`

Hope that helps!
